version: '3.4'

services:

  fake_packagist_server:
    image: php:7.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./badge/src/Infrastructure/FakePackagistServer:/srv/app:cached
    entrypoint: ["php", "-S", "0.0.0.0:80", "/srv/app/router.php"]
