version: '3.4'

services:

  fake_github_server:
    image: php:7.4-alpine
    ports:
      - "8081:80"
    volumes:
      - ./badge/src/Infrastructure/FakeGithubServer:/srv/app:cached
    entrypoint: ["php", "-S", "0.0.0.0:80", "/srv/app/router.php"]

  fake_server_acceptance_test:
    image: php:7.4-alpine
    ports:
      - "8082:80"
    volumes:
      - ./badge/tests/Acceptance/FakeAllInOneApiServer:/srv/app:cached
    entrypoint: ["php", "-S", "0.0.0.0:80", "/srv/app/index.php"]

  api_mock_server:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - "8888:1080"